/** Orden de las categorías en el selector de materiales: primero suelos, después paredes, fachada y exterior. */
export const SURFACE_CATEGORY_ORDER = [
  'Parqué y tarima', 'Baldosas y porcelánico', 'Baldosa hidráulica y barro', 'Mármol', 'Piedra y terrazo',
  'Microcemento y hormigón', 'Moqueta', 'Azulejo de pared', 'Pintura y estuco', 'Ladrillo visto',
  'Madera (paredes y muebles)', 'Fachada', 'Tela', 'Exterior',
] as const;

/**
 * Nombre y categoría en español de la primera biblioteca de Poly Haven (public/materials/polyhaven), que guardaba el
 * título original en inglés. Los ids no cambian: los planos guardados siguen apuntando al mismo material.
 */
export const LEGACY_SURFACE_NAMES: Readonly<Record<string, readonly [label: string, category: string]>> = {
  'polyhaven:grass_ground': ['Césped natural PBR', 'Exterior'],
  'polyhaven:wood_floor': ['Tarima de madera natural', 'Parqué y tarima'],
  'polyhaven:wooden_floor_01': ['Tarima de tablillas mixtas', 'Parqué y tarima'],
  'polyhaven:wooden_floor_02': ['Tarima de tablillas claras', 'Parqué y tarima'],
  'polyhaven:herringbone_parquet': ['Parqué en espiga', 'Parqué y tarima'],
  'polyhaven:diagonal_parquet': ['Parqué en diagonal', 'Parqué y tarima'],
  'polyhaven:rectangular_parquet': ['Parqué de tablillas', 'Parqué y tarima'],
  'polyhaven:oak_wood_planks': ['Tablas de roble', 'Parqué y tarima'],
  'polyhaven:dark_wood': ['Madera de caoba', 'Madera (paredes y muebles)'],
  'polyhaven:kitchen_wood': ['Madera de roble veteada', 'Madera (paredes y muebles)'],
  'polyhaven:fine_grained_wood': ['Madera oscura de grano fino', 'Madera (paredes y muebles)'],
  'polyhaven:dark_paneled_wood': ['Panel de madera oscura', 'Madera (paredes y muebles)'],
  'polyhaven:wood_plank_wall': ['Tablas de madera para pared', 'Madera (paredes y muebles)'],
  'polyhaven:interior_tiles': ['Baldosa beige en diagonal', 'Baldosas y porcelánico'],
  'polyhaven:grey_tiles': ['Baldosa gris oliva', 'Baldosas y porcelánico'],
  'polyhaven:long_white_tiles': ['Azulejo blanco alargado', 'Azulejo de pared'],
  'polyhaven:square_tiles': ['Pavimento de mosaico gris', 'Exterior'],
  'polyhaven:square_tiles_02': ['Pavimento de mosaico multicolor', 'Exterior'],
  'polyhaven:square_tiles_03': ['Pavimento de losetas grises', 'Exterior'],
  'polyhaven:floor_tiles_02': ['Losa de piedra gris clara', 'Piedra y terrazo'],
  'polyhaven:floor_tiles_04': ['Losa de piedra caliza beige', 'Piedra y terrazo'],
  'polyhaven:floor_tiles_06': ['Baldosa ajedrezada gris', 'Baldosas y porcelánico'],
  'polyhaven:floor_tiles_08': ['Baldosa de piedra beige', 'Baldosas y porcelánico'],
  'polyhaven:terracotta_floor_tiles': ['Baldosa de barro rojo', 'Baldosa hidráulica y barro'],
  'polyhaven:terrazzo_tiles': ['Terrazo marrón', 'Piedra y terrazo'],
  'polyhaven:marble_01': ['Mármol crema en losas', 'Mármol'],
  'polyhaven:marble_tiles': ['Mosaico de mármol gris', 'Mármol'],
  'polyhaven:marble_mosaic_tiles': ['Mosaico de mármol ajedrezado', 'Mármol'],
  'polyhaven:stone_wall': ['Muro de mampostería', 'Fachada'],
  'polyhaven:stone_wall_02': ['Muro de piedra oscura', 'Fachada'],
  'polyhaven:stacked_stone_wall': ['Muro de piedra apilada', 'Fachada'],
  'polyhaven:stone_tiles': ['Losas de piedra irregulares verdes', 'Piedra y terrazo'],
  'polyhaven:stone_tiles_02': ['Losas de piedra irregulares grises', 'Piedra y terrazo'],
  'polyhaven:patterned_slate_tiles': ['Pizarra en espiga', 'Piedra y terrazo'],
  'polyhaven:concrete': ['Hormigón visto', 'Microcemento y hormigón'],
  'polyhaven:concrete_floor': ['Solera de hormigón ocre', 'Microcemento y hormigón'],
  'polyhaven:concrete_floor_01': ['Hormigón con árido visto', 'Microcemento y hormigón'],
  'polyhaven:brushed_concrete': ['Hormigón cepillado', 'Microcemento y hormigón'],
  'polyhaven:brushed_concrete_03': ['Hormigón cepillado claro', 'Microcemento y hormigón'],
  'polyhaven:concrete_tiles': ['Losetas de hormigón', 'Exterior'],
  'polyhaven:concrete_tiles_02': ['Losas de hormigón alargadas', 'Exterior'],
  'polyhaven:brick_wall_001': ['Ladrillo visto rústico', 'Ladrillo visto'],
  'polyhaven:brick_wall_003': ['Ladrillo visto beige', 'Ladrillo visto'],
  'polyhaven:brick_4': ['Ladrillo rojo clásico', 'Ladrillo visto'],
  'polyhaven:brick_floor': ['Suelo de ladrillo en espiga', 'Exterior'],
  'polyhaven:brick_floor_02': ['Suelo de ladrillo marrón', 'Exterior'],
  'polyhaven:brick_floor_04': ['Suelo de ladrillo oscuro', 'Exterior'],
  'polyhaven:brick_pavement': ['Adoquín de ladrillo rojo', 'Exterior'],
  'polyhaven:brick_pavement_02': ['Adoquín de ladrillo oscuro', 'Exterior'],
  'polyhaven:grey_plaster': ['Yeso gris envejecido', 'Pintura y estuco'],
  'polyhaven:grey_plaster_02': ['Yeso gris cálido', 'Pintura y estuco'],
  'polyhaven:grey_plaster_03': ['Yeso color arena', 'Pintura y estuco'],
  'polyhaven:painted_plaster_wall': ['Pared pintada gris perla', 'Pintura y estuco'],
  'polyhaven:white_plaster_02': ['Pintura blanca lisa', 'Pintura y estuco'],
  'polyhaven:white_plaster_rough_01': ['Yeso rugoso envejecido', 'Pintura y estuco'],
  'polyhaven:clay_plaster': ['Revoco de barro', 'Pintura y estuco'],
  'polyhaven:patterned_clay_plaster': ['Revoco de arcilla decorativo', 'Pintura y estuco'],
  'polyhaven:fabric_pattern_05': ['Tela de cuadros verde', 'Tela'],
  'polyhaven:fabric_pattern_07': ['Tela vichy roja', 'Tela'],
  'polyhaven:fabric_leather_01': ['Piel marrón', 'Tela'],
  'polyhaven:quatrefoil_jacquard_fabric': ['Jacquard granate', 'Tela'],
};
